const ActionTypes = {
  GET_BOOKS: 'GET_BOOKS',
  GOT_BOOKS: 'GOT_BOOKS',
  ADD_BOOK: 'ADD_BOOK',
  UPDATE_BOOK_LIST: 'UPDATE_BOOK_LIST',
  FILTER_BOOKS: 'FILTER_BOOKS',
  UPDATE_BOOK: 'UPDATE_BOOK',
  DELETE_BOOK: 'DELETE_BOOK'
};

export default ActionTypes;
